const data = [
  {
    id: "1",
    name: "Shopping List",
    created: "April 20, 2021",
    category: "Task",
    content: "Tomatoes, bread",
    dates: "",
    archived: false,
  },
  {
    id: "2",
    name: "The theory of evolution",
    created: "April 27, 2021",
    category: "Random Thought",
    content: "The evolution",
    dates: "",
    archived: false,
  },
  {
    id: "3",
    name: "New Feature",
    created: "May 05, 2021",
    category: "Idea",
    content: "Implement new...",
    dates: "3/5/2021, 5/5/2021",
    archived: false,
  },
  {
    id: "4",
    name: "William Gaddis",
    created: "May 07, 2021",
    category: "Quote",
    content: "Power doesn't co...",
    dates: "",
    archived: false,
  },
  {
    id: "5",
    name: "Books",
    created: "May 15, 2021",
    category: "Task",
    content: "The Lean Startup",
    dates: "",
    archived: true,
  },
];
export default data;
